language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version
  - docker-compose --version
  - docker-compose build --parallel
  - docker images ps

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/reverseproxy
  - docker push $DOCKER_USERNAME/udagram-api-user
  - docker push $DOCKER_USERNAME/udagram-api-feed
  - docker push $DOCKER_USERNAME/udagram-frontend