language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version
  - docker-compose --version
  - docker-compose build --parallel

after_success:
  - docker images
  - docker login -u "$DOCKER_USERNAME" -p $DOCKER_PASSWORD
  - docker-compose push